package subscriber.child

case class ChildRecord(statecode: String,
                       districtcode: String,
                       projectcode: String,
                       sectorcode: String,
                       aanganwadicode: String,
                       childcode: String,
                       weight: String,
                       height: String,
                       bmi: String,
                       whounderweight: String,
                       iap: String,
                       day: String,
                       month: String,
                       year: String,
                       wasting: String,
                       stunting: String,
                       minutes: String,
                       hours: String,
                       dayofbirth: String,
                       monthofbirth: String,
                       yearofbirth: String,
                       address: String,
                       sex: String,
                       category: String,
                       fathername: String,
                       name: String,
                       age: String) {

}
